apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  namespace: default
  labels:
    app: db
spec:
  selector:
    matchLabels:
      app: db
  replicas: 1  
  template:
    metadata:
      labels:
        app: db
    spec:    
      containers:
      - name: postgres
        image: postgres:15-alpine
        env:
        - name: POSTGRES_USER          
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD          
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: POSTGRES_PASSWORD      
        ports:
        - containerPort: 5432
          name: postgres


---
apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: default
spec:
  selector:
    app: db
  type: ClusterIP
  ports:
  - name: db 
    protocol: TCP
    port: 5432
    targetPort: 5432                    