apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deploy
  namespace: default
  labels:
    app: redis
spec:
  selector:
    matchLabels:
      app: redis
  replicas: 1  
  template:
    metadata:
      labels:
        app: redis
    spec:    
      containers:
      - name: redis
        image: redis:alpine             
        ports:
        - containerPort: 6379



---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: default
spec:
  selector:
    app: redis
  type: ClusterIP
  ports:
  - name: redis 
    protocol: TCP
    port: 6379
    targetPort: 6379                    