apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deploy
  namespace: default
  labels:
    app: worker
spec:
  selector:
    matchLabels:
      app: worker
  replicas: 1 
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker
        image: dockersamples/examplevotingapp_worker