apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deploy
  namespace: default
  labels:
    app: mongo-express
spec:
  selector:
    matchLabels:
      app: mongo-express
  replicas: 1 
  template:
    metadata:
      labels:
        app: mongo-express
    spec:
      containers:
      - name: mongo-express
        image: mongo-express:0.54.0
        env:
        - name: ME_CONFIG_MONGODB_SERVER          
          valueFrom:
            configMapKeyRef:
              name: mongo-config
              key: SERVER
        - name: ME_CONFIG_BASICAUTH          
          valueFrom:
            configMapKeyRef:
              name: mongo-config
              key: ME_CONFIG_BASICAUTH
        - name: ME_CONFIG_MONGODB_ADMINPASSWORD                  
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: ME_CONFIG_MONGODB_ADMINPASSWORD
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME          
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: ME_CONFIG_MONGODB_ADMINUSERNAME 
        - name: ME_CONFIG_BASICAUTH_USERNAME          
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: ME_CONFIG_BASICAUTH_USERNAME 
        - name: ME_CONFIG_BASICAUTH_PASSWORD          
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: ME_CONFIG_BASICAUTH_PASSWORD                       
        ports:
        - containerPort: 8081          
          name: mongo-express


---
apiVersion: v1
kind: Service
metadata:
  name: mongo-express-svc
  namespace: default
spec:
  selector:
    app: mongo-express
  type: LoadBalancer
  ports:
  - name: mongo-express
    protocol: TCP
    port: 8081
    targetPort: 8081         