apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: default
  labels:
    app: mongodb
spec:
  selector:
    matchLabels:
      app: mongodb
  replicas: 1  
  template:
    metadata:
      labels:
        app: mongodb
    spec:    
      containers:
      - name: mongodb
        image: mongo:4.4.3
        env:
        - name: MONGO_INITDB_ROOT_USERNAME          
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: MONGO_INITDB_ROOT_USERNAME
        - name: MONGO_INITDB_ROOT_PASSWORD          
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: MONGO_INITDB_ROOT_PASSWORD      
        ports:
        - containerPort: 27017
          name: mongo


---
apiVersion: v1
kind: Service
metadata:
  name: mongo-svc
  namespace: default
spec:
  selector:
    app: mongodb
  type: ClusterIP
  ports:
  - name: mongo-svc 
    protocol: TCP
    port: 27017
    targetPort: 27017                    