apiVersion: v1
kind: Secret
metadata:
  name: mysecret
  namespace: default
type: Opaque
data:
  MONGO_INITDB_ROOT_USERNAME: cm9vdA==
  MONGO_INITDB_ROOT_PASSWORD: UGFzc1cwOUAh
  ME_CONFIG_MONGODB_ADMINUSERNAME: cm9vdA==
  ME_CONFIG_MONGODB_ADMINPASSWORD: UGFzc1cwOUAh 
  ME_CONFIG_BASICAUTH_USERNAME: YWRtaW4=
  ME_CONFIG_BASICAUTH_PASSWORD: cGFzcw==